name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider:
  shared_preferences: ^2.0.0

  equatable: ^2.0.5

  pie_chart: 5.4.0
  fl_chart: ^0.35.0
  syncfusion_flutter_gauges: ^25.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
